---
- name: Add the repository key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Add the repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_8.x {{ubuntu_codename}} main"
    state: present
    update_cache: yes

- name: Add the repository
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_8.x {{ubuntu_codename}} main"
    state: present
    update_cache: yes

- name: Install nodejs
  apt:
    name: "{{item}}"
    state: latest
  with_items:
  - nodejs

- name: Install yarn
  npm:
    name: yarn
    global: yes
    state: latest
